import type { HighlightTheme } from './types'

/**
 * VS Code Dark+ 风格主题
 */
export const darkPlusTheme: HighlightTheme = {
  id: 'dark-plus',
  displayName: 'Dark+',
  defaultStyle: 'color: #D4D4D4;',
  preStyle:
    "background: #1E1E1E; padding: 16px; border-radius: 8px; font-family: 'Consolas', 'Monaco', monospace; font-size: 14px; line-height: 1.5; white-space: pre;",
  styles: {
    'comment.line.double-slash.js': 'color: #6A9955;',
    'comment.block.js': 'color: #6A9955; font-style: italic;',
    'comment.line.number-sign.python': 'color: #6A9955;',
    'comment.line.number-sign.bash': 'color: #6A9955;',
    'comment.line.number-sign.yaml': 'color: #6A9955;',
    'comment.line.double-dash.sql': 'color: #6A9955;',
    'comment.line.double-slash.java': 'color: #6A9955;',
    'comment.line.double-slash.c': 'color: #6A9955;',
    'comment.line.double-slash.cpp': 'color: #6A9955;',
    'comment.line.double-slash.csharp': 'color: #6A9955;',
    'comment.line.double-slash.php': 'color: #6A9955;',
    'comment.line.number-sign.php': 'color: #6A9955;',
    'comment.line.double-slash.rust': 'color: #6A9955;',
    'comment.line.double-slash.go': 'color: #6A9955;',
    'comment.block.html': 'color: #6A9955; font-style: italic;',
    'comment.block.css': 'color: #6A9955; font-style: italic;',
    'comment.block.sql': 'color: #6A9955; font-style: italic;',
    'comment.block.markdown': 'color: #6A9955; font-style: italic;',
    'comment.block.java': 'color: #6A9955; font-style: italic;',
    'comment.block.c': 'color: #6A9955; font-style: italic;',
    'comment.block.cpp': 'color: #6A9955; font-style: italic;',
    'comment.block.csharp': 'color: #6A9955; font-style: italic;',
    'comment.block.php': 'color: #6A9955; font-style: italic;',
    'comment.block.rust': 'color: #6A9955; font-style: italic;',
    'comment.block.go': 'color: #6A9955; font-style: italic;',

    'keyword.control.js': 'color: #569CD6;',
    'keyword.control.async.js': 'color: #C586C0;',
    'keyword.control.class.js': 'color: #569CD6; font-weight: bold;',
    'keyword.control.module.js': 'color: #569CD6;',
    'keyword.control.import.js': 'color: #569CD6;',
    'keyword.declaration.js': 'color: #569CD6;',
    'keyword.declaration.type.typescript': 'color: #569CD6; font-weight: bold;',
    'keyword.modifier.access.typescript': 'color: #4EC9B0;',
    'keyword.operator.assertion.typescript': 'color: #C586C0;',
    'keyword.operator.type.typescript': 'color: #C586C0;',
    'keyword.control.python': 'color: #569CD6;',
    'keyword.control.bash': 'color: #569CD6;',
    'keyword.control.sql': 'color: #569CD6;',
    'keyword.control.java': 'color: #569CD6;',
    'keyword.declaration.java': 'color: #569CD6; font-weight: bold;',
    'keyword.modifier.java': 'color: #4EC9B0;',
    'keyword.control.directive.c': 'color: #569CD6; font-weight: bold;',
    'keyword.control.c': 'color: #569CD6;',
    'keyword.declaration.c': 'color: #569CD6; font-weight: bold;',
    'keyword.modifier.c': 'color: #4EC9B0;',
    'keyword.control.directive.cpp': 'color: #569CD6; font-weight: bold;',
    'keyword.control.cpp': 'color: #569CD6;',
    'keyword.declaration.cpp': 'color: #569CD6; font-weight: bold;',
    'keyword.modifier.cpp': 'color: #4EC9B0;',
    'keyword.control.go': 'color: #569CD6;',
    'keyword.declaration.go': 'color: #569CD6; font-weight: bold;',
    'keyword.control.rust': 'color: #569CD6;',
    'keyword.declaration.rust': 'color: #569CD6; font-weight: bold;',
    'keyword.modifier.rust': 'color: #4EC9B0;',
    'keyword.control.csharp': 'color: #569CD6;',
    'keyword.declaration.csharp': 'color: #569CD6; font-weight: bold;',
    'keyword.modifier.csharp': 'color: #4EC9B0;',
    'keyword.control.php': 'color: #569CD6;',
    'keyword.declaration.php': 'color: #569CD6; font-weight: bold;',
    'keyword.modifier.php': 'color: #4EC9B0;',
    'keyword.control.document.begin.yaml': 'color: #569CD6;',
    'keyword.control.document.end.yaml': 'color: #569CD6;',
    'markup.heading.markdown': 'color: #569CD6; font-weight: bold;',
    'markup.heading.setext.markdown': 'color: #569CD6; font-weight: bold;',
    'keyword.declaration.function.bash': 'color: #569CD6; font-weight: bold;',
    'keyword.declaration.python': 'color: #569CD6; font-weight: bold;',
    'entity.name.function.python': 'color: #DCDCAA;',
    'entity.name.class.python': 'color: #4EC9B0;',
    'entity.name.function.bash': 'color: #DCDCAA;',
    'support.function.builtin.python': 'color: #DCDCAA; font-weight: bold;',
    'support.function.builtin.bash': 'color: #DCDCAA; font-weight: bold;',
    'support.function.builtin.sql': 'color: #DCDCAA; font-weight: bold;',
    'entity.name.function.java': 'color: #DCDCAA;',
    'support.type.annotation.python': 'color: #4EC9B0;',
    'meta.decorator.python': 'color: #C586C0;',
    'keyword.control.doctype.html': 'color: #C586C0;',
    'keyword.control.at-rule.css': 'color: #C586C0;',
    'keyword.other.important.css': 'color: #D16969; font-weight: bold;',
    'meta.preprocessor.c': 'color: #C586C0;',
    'meta.preprocessor.cpp': 'color: #C586C0;',
    'meta.preprocessor.csharp': 'color: #C586C0;',
    'meta.attribute.rust': 'color: #C586C0;',
    'meta.attribute.csharp': 'color: #C586C0;',
    'meta.attribute.php': 'color: #C586C0;',
    'meta.tag.php': 'color: #C586C0;',

    'constant.language.boolean.js': 'color: #569CD6;',
    'constant.language.null.js': 'color: #569CD6;',
    'constant.language.js': 'color: #569CD6;',
    'constant.numeric.js': 'color: #B5CEA8;',
    'constant.language.boolean.json': 'color: #569CD6;',
    'constant.language.null.json': 'color: #569CD6;',
    'constant.numeric.json': 'color: #B5CEA8;',
    'constant.language.boolean.python': 'color: #569CD6;',
    'constant.language.boolean.sql': 'color: #569CD6;',
    'constant.language.boolean.yaml': 'color: #569CD6;',
    'constant.language.none.python': 'color: #569CD6;',
    'constant.language.null.sql': 'color: #569CD6;',
    'constant.language.null.yaml': 'color: #569CD6;',
    'constant.language.boolean.java': 'color: #569CD6;',
    'constant.language.null.java': 'color: #569CD6;',
    'constant.language.boolean.c': 'color: #569CD6;',
    'constant.language.null.c': 'color: #569CD6;',
    'constant.language.boolean.cpp': 'color: #569CD6;',
    'constant.language.null.cpp': 'color: #569CD6;',
    'constant.language.boolean.go': 'color: #569CD6;',
    'constant.language.null.go': 'color: #569CD6;',
    'constant.language.iota.go': 'color: #C586C0;',
    'constant.language.boolean.rust': 'color: #569CD6;',
    'constant.language.null.rust': 'color: #569CD6;',
    'constant.language.boolean.csharp': 'color: #569CD6;',
    'constant.language.null.csharp': 'color: #569CD6;',
    'constant.language.boolean.php': 'color: #569CD6;',
    'constant.language.null.php': 'color: #569CD6;',
    'constant.language.php': 'color: #569CD6;',
    'constant.numeric.python': 'color: #B5CEA8;',
    'constant.numeric.bash': 'color: #B5CEA8;',
    'constant.numeric.sql': 'color: #B5CEA8;',
    'constant.numeric.yaml': 'color: #B5CEA8;',
    'constant.numeric.java': 'color: #B5CEA8;',
    'constant.numeric.css': 'color: #B5CEA8;',
    'constant.numeric.c': 'color: #B5CEA8;',
    'constant.numeric.cpp': 'color: #B5CEA8;',
    'constant.numeric.go': 'color: #B5CEA8;',
    'constant.numeric.rust': 'color: #B5CEA8;',
    'constant.numeric.csharp': 'color: #B5CEA8;',
    'constant.numeric.php': 'color: #B5CEA8;',
    'constant.other.color.hex.css': 'color: #D7BA7D;',
    'variable.language.global-this.js': 'color: #C586C0; font-weight: bold;',
    'variable.language.special.bash': 'color: #C586C0; font-weight: bold;',
    'support.type.builtin.typescript': 'color: #4EC9B0;',
    'variable.parameter.bash': 'color: #9CDCFE;',
    'variable.parameter.sql': 'color: #9CDCFE;',
    'variable.other.readwrite.bash': 'color: #9CDCFE;',
    'variable.parameter.custom-property.css': 'color: #4EC9B0;',
    'variable.language.java': 'color: #C586C0; font-weight: bold;',
    'variable.language.csharp': 'color: #C586C0; font-weight: bold;',
    'variable.language.php': 'color: #C586C0; font-weight: bold;',
    'variable.other.php': 'color: #9CDCFE;',

    'string.quoted.double.js': 'color: #CE9178;',
    'string.quoted.single.js': 'color: #CE9178;',
    'string.quoted.backtick.js': 'color: #CE9178;',
    'string.quoted.double.json': 'color: #CE9178;',
    'string.quoted.double.python': 'color: #CE9178;',
    'string.quoted.single.python': 'color: #CE9178;',
    'string.quoted.double.bash': 'color: #CE9178;',
    'string.quoted.single.bash': 'color: #CE9178;',
    'string.quoted.double.sql': 'color: #CE9178;',
    'string.quoted.single.sql': 'color: #CE9178;',
    'string.quoted.double.java': 'color: #CE9178;',
    'string.quoted.single.java': 'color: #CE9178;',
    'string.quoted.triple.java': 'color: #CE9178;',
    'string.quoted.angle.c': 'color: #D7BA7D;',
    'string.quoted.double.c': 'color: #CE9178;',
    'string.quoted.single.c': 'color: #CE9178;',
    'string.quoted.angle.cpp': 'color: #D7BA7D;',
    'string.quoted.double.cpp': 'color: #CE9178;',
    'string.quoted.single.cpp': 'color: #CE9178;',
    'string.quoted.raw.cpp': 'color: #CE9178;',
    'string.quoted.double.go': 'color: #CE9178;',
    'string.quoted.single.go': 'color: #CE9178;',
    'string.quoted.raw.go': 'color: #CE9178;',
    'string.quoted.double.rust': 'color: #CE9178;',
    'string.quoted.single.rust': 'color: #CE9178;',
    'string.quoted.raw.rust': 'color: #CE9178;',
    'string.quoted.double.csharp': 'color: #CE9178;',
    'string.quoted.single.csharp': 'color: #CE9178;',
    'string.quoted.verbatim.csharp': 'color: #CE9178;',
    'string.quoted.raw.csharp': 'color: #CE9178;',
    'string.quoted.double.php': 'color: #CE9178;',
    'string.quoted.single.php': 'color: #CE9178;',
    'string.quoted.backtick.php': 'color: #CE9178;',
    'string.quoted.double.yaml': 'color: #CE9178;',
    'string.quoted.single.yaml': 'color: #CE9178;',
    'string.unquoted.yaml': 'color: #CE9178;',
    'markup.inline.raw.markdown': 'color: #CE9178;',
    'markup.code.indented.markdown': 'color: #CE9178;',
    'string.unquoted.markdown': 'color: #D4D4D4;',
    'string.quoted.double.triple.python': 'color: #CE9178;',
    'string.quoted.single.triple.python': 'color: #CE9178;',
    'string.interpolated.python': 'color: #CE9178;',
    'string.quoted.double.html': 'color: #CE9178;',
    'string.quoted.single.html': 'color: #CE9178;',
    'string.unquoted.html': 'color: #CE9178;',
    'string.quoted.double.css': 'color: #CE9178;',
    'string.quoted.single.css': 'color: #CE9178;',

    'operator.js': 'color: #D4D4D4;',
    'operator.optional-chaining.js': 'color: #DCDCAA; font-weight: bold;',
    'operator.nullish-coalescing.js': 'color: #DCDCAA; font-weight: bold;',
    'operator.arrow-function.js': 'color: #DCDCAA;',
    'operator.python': 'color: #D4D4D4;',
    'operator.bash': 'color: #D4D4D4;',
    'keyword.operator.sql': 'color: #D4D4D4;',
    'operator.css': 'color: #D4D4D4;',
    'operator.java': 'color: #D4D4D4;',
    'operator.c': 'color: #D4D4D4;',
    'operator.cpp': 'color: #D4D4D4;',
    'operator.go': 'color: #D4D4D4;',
    'operator.rust': 'color: #D4D4D4;',
    'operator.csharp': 'color: #D4D4D4;',
    'operator.php': 'color: #D4D4D4;',

    'punctuation.definition.template-expression.js': 'color: #C586C0;',
    'punctuation.separator.key-value.json': 'color: #D4D4D4;',
    'punctuation.separator.value.json': 'color: #D4D4D4;',
    'meta.structure.dictionary.json': 'color: #D4D4D4;',
    'meta.structure.array.json': 'color: #D4D4D4;',
    'punctuation.separator.comma.sql': 'color: #D4D4D4;',
    'punctuation.terminator.statement.sql': 'color: #D4D4D4;',
    'punctuation.section.group.begin.sql': 'color: #808080;',
    'punctuation.section.group.end.sql': 'color: #808080;',
    'punctuation.separator.key-value.yaml': 'color: #D4D4D4;',
    'punctuation.definition.sequence.item.yaml': 'color: #D4D4D4;',
    'punctuation.section.flow.yaml': 'color: #808080;',
    'markup.fenced-code.block.begin.markdown': 'color: #808080;',
    'markup.fenced-code.block.end.markdown': 'color: #808080;',
    'markup.table.separator.markdown': 'color: #808080;',
    'markup.hr.markdown': 'color: #808080;',
    'markup.link.punctuation.markdown': 'color: #808080;',
    'punctuation.definition.interpolation.begin.python': 'color: #C586C0;',
    'punctuation.definition.interpolation.end.python': 'color: #C586C0;',
    'punctuation.format.fstring.python': 'color: #D7BA7D;',
    'punctuation.definition.tag.begin.html': 'color: #808080;',
    'punctuation.definition.tag.end.html': 'color: #808080;',
    'punctuation.separator.key-value.html': 'color: #D4D4D4;',
    'punctuation.section.block.begin.css': 'color: #808080;',
    'punctuation.section.block.end.css': 'color: #808080;',
    'punctuation.separator.key-value.css': 'color: #D4D4D4;',
    'punctuation.separator.selector.css': 'color: #D4D4D4;',
    'punctuation.terminator.rule.css': 'color: #D4D4D4;',
    'punctuation.definition.attribute.begin.css': 'color: #808080;',
    'punctuation.definition.attribute.end.css': 'color: #808080;',

    'variable.identifier.js': 'color: #9CDCFE;',
    'entity.name.type.typescript': 'color: #4EC9B0;',
    'entity.name.tag.html': 'color: #569CD6;',
    'entity.other.attribute-name.html': 'color: #9CDCFE;',
    'entity.name.tag.css': 'color: #569CD6;',
    'entity.other.attribute-name.class.css': 'color: #4EC9B0;',
    'entity.other.attribute-name.id.css': 'color: #C586C0;',
    'entity.other.attribute-name.pseudo-class.css': 'color: #DCDCAA;',
    'entity.other.attribute-name.pseudo-element.css': 'color: #DCDCAA;',
    'variable.alias.python': 'color: #9CDCFE; font-style: italic;',
    'variable.comprehension.python': 'color: #9CDCFE;',
    'variable.identifier.python': 'color: #9CDCFE;',
    'entity.name.command.bash': 'color: #D4D4D4;',
    'entity.name.table.sql': 'color: #4EC9B0;',
    'entity.name.column.sql': 'color: #9CDCFE;',
    'entity.name.type.java': 'color: #4EC9B0;',
    'entity.name.namespace.java': 'color: #9CDCFE;',
    'meta.annotation.java': 'color: #C586C0;',
    'support.type.builtin.java': 'color: #4EC9B0;',
    'entity.name.type.c': 'color: #4EC9B0;',
    'entity.name.function.c': 'color: #DCDCAA;',
    'entity.name.macro.c': 'color: #C586C0;',
    'support.type.builtin.c': 'color: #4EC9B0;',
    'entity.name.type.cpp': 'color: #4EC9B0;',
    'entity.name.function.cpp': 'color: #DCDCAA;',
    'entity.name.namespace.cpp': 'color: #9CDCFE;',
    'entity.name.macro.cpp': 'color: #C586C0;',
    'support.type.builtin.cpp': 'color: #4EC9B0;',
    'entity.name.type.go': 'color: #4EC9B0;',
    'entity.name.function.go': 'color: #DCDCAA;',
    'entity.name.namespace.go': 'color: #9CDCFE;',
    'support.type.builtin.go': 'color: #4EC9B0;',
    'entity.name.type.rust': 'color: #4EC9B0;',
    'entity.name.function.rust': 'color: #DCDCAA;',
    'entity.name.namespace.rust': 'color: #9CDCFE;',
    'entity.name.macro.rust': 'color: #C586C0;',
    'support.type.builtin.rust': 'color: #4EC9B0;',
    'variable.language.rust': 'color: #C586C0; font-weight: bold;',
    'entity.name.type.csharp': 'color: #4EC9B0;',
    'entity.name.function.csharp': 'color: #DCDCAA;',
    'entity.name.namespace.csharp': 'color: #9CDCFE;',
    'support.type.builtin.csharp': 'color: #4EC9B0;',
    'entity.name.type.php': 'color: #4EC9B0;',
    'entity.name.function.php': 'color: #DCDCAA;',
    'entity.name.namespace.php': 'color: #9CDCFE;',
    'support.type.builtin.php': 'color: #4EC9B0;',
    'support.type.property-name.yaml': 'color: #9CDCFE;',
    'entity.name.tag.anchor.yaml': 'color: #4EC9B0;',
    'variable.other.alias.yaml': 'color: #9CDCFE; font-style: italic;',
    'entity.name.tag.yaml': 'color: #C586C0;',
    'markup.quote.markdown': 'color: #6A9955; font-style: italic;',
    'markup.list.markdown': 'color: #D7BA7D;',
    'markup.task.markdown': 'color: #D7BA7D; font-weight: bold;',
    'markup.table.row.markdown': 'color: #D4D4D4;',
    'markup.bold.markdown': 'color: #DCDCAA; font-weight: bold;',
    'markup.italic.markdown': 'color: #DCDCAA; font-style: italic;',
    'markup.strikethrough.markdown': 'color: #D7BA7D; text-decoration: line-through;',
    'markup.link.label.markdown': 'color: #4EC9B0;',
    'markup.link.url.markdown': 'color: #9CDCFE; text-decoration: underline;',
    'markup.image.label.markdown': 'color: #4EC9B0;',
    'markup.reference.link.label.markdown': 'color: #4EC9B0; font-style: italic;',
    'markup.reference.link.url.markdown': 'color: #9CDCFE; text-decoration: underline;',
    'support.function.promise.js': 'color: #DCDCAA; font-weight: bold;',
    'support.function.css': 'color: #DCDCAA;',
    'support.type.property-name.css': 'color: #9CDCFE;',
    'constant.character.entity.html': 'color: #D7BA7D;',
    'text.plain.html': 'color: #D4D4D4;',

    default: 'color: #D4D4D4;'
  }
}
